import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {evolveNumeric} from '@metaharness/darwin';
export const sha=x=>crypto.createHash('sha256').update(x).digest('hex');
export function validateGenome(genome,spec){for(const [k,s] of Object.entries(spec)){const v=genome[k];if(!Number.isFinite(v)||v<s.min||v>s.max||!['linear','log'].includes(s.scale)||!['float','int'].includes(s.type)||(s.scale==='log'&&s.min<=0))throw Error('invalid genome '+k);}return true;}
export function freshRoot(root){if(fs.existsSync(root))throw Error('workRoot must be fresh');fs.mkdirSync(path.dirname(root),{recursive:true});}
export async function safeEvaluate(fn,genome,variantId,timeoutMs){try{const value=await Promise.race([Promise.resolve().then(()=>fn(genome,variantId)),new Promise((_,reject)=>setTimeout(()=>reject(Error('timeout')),timeoutMs))]);if(!value||![value.error,value.brier].every(Number.isFinite))throw Error('nonfinite metrics');return {variantId,primary:-value.error,regressed:Boolean(value.regressed),noopRate:0,costPerWin:value.elapsedMs??0,raw:value};}catch(error){return {variantId,primary:-Number.MAX_VALUE,regressed:true,noopRate:1,costPerWin:Infinity,raw:{fault:String(error?.message||error)}};}}
export function canonical(records){return records.map(r=>{const raw=r.score?.raw?Object.fromEntries(Object.entries(r.score.raw).filter(([k])=>k!=='elapsedMs')):r.score?.raw;return{id:r.variant.id,parentId:r.variant.parentId,generation:r.variant.generation,genome:r.variant.genome,mutatedParams:r.variant.mutatedParams,score:r.score&&{primary:r.score.primary,regressed:r.score.regressed,raw}};});}
export function admissible(result){return result.records.filter(r=>r.score&&!r.score.regressed&&Number.isFinite(r.score.primary)&&r.score.raw&&Number.isFinite(r.score.raw.error)&&Number.isFinite(r.score.raw.brier)).sort((a,b)=>b.score.primary-a.score.primary||a.variant.id.localeCompare(b.variant.id));}
export function decide(parent,candidate,guard){const reasons=[];if(!candidate)reasons.push('no admissible candidate');else{const rel=(parent.error-candidate.error)/parent.error;if(rel<guard.required_relative_error_reduction)reasons.push('insufficient improvement');if(candidate.brier>parent.brier*(1+guard.maximum_relative_brier_regression))reasons.push('brier regression');if(![candidate.error,candidate.brier].every(Number.isFinite))reasons.push('nonfinite metric');}return {retain:reasons.length===0,reasons};}
export async function runDarwin({protocol,workRoot,evaluate}){freshRoot(workRoot);let count=0;const evaluator={evaluate:async(g,id)=>{if(++count>protocol.guard.max_evaluations)return {variantId:id,primary:-Number.MAX_VALUE,regressed:true,noopRate:1,costPerWin:Infinity,raw:{fault:'budget'}};validateGenome(g,protocol.genome_spec);return safeEvaluate(evaluate,g,id,protocol.guard.evaluation_timeout_ms);}};const result=await evolveNumeric({genomeSpec:protocol.genome_spec,evaluator,generations:protocol.darwin.generations,childrenPerGeneration:protocol.darwin.children_per_generation,seed:protocol.darwin.seed,concurrency:protocol.darwin.concurrency,mutationSigma:protocol.darwin.mutation_sigma,crossover:protocol.darwin.crossover,baselineGenome:protocol.baseline_genome,workRoot});return {result,count,admissible:admissible(result)};}
export function atomicActivate(root,parentDigest,candidate,health=true){fs.mkdirSync(root,{recursive:true});const active=path.join(root,'active.json'),parent={digest:parentDigest,status:'development_parent'};fs.writeFileSync(active,JSON.stringify(parent));if(!candidate)return {retained:false,rolledBack:false,active:parent};const next={digest:sha(JSON.stringify(candidate)),status:'development_champion',genome:candidate};const tmp=active+'.tmp';fs.writeFileSync(tmp,JSON.stringify(next));fs.renameSync(tmp,active);if(!health){const rollback=active+'.rollback';fs.writeFileSync(rollback,JSON.stringify(parent));fs.renameSync(rollback,active);return {retained:false,rolledBack:true,active:JSON.parse(fs.readFileSync(active))};}return {retained:true,rolledBack:false,active:JSON.parse(fs.readFileSync(active))};}
